# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Instabook' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instabook
  pod 'Firebase', '>=2.5.1'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/AdMob'
  target 'InstabookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
